### ISSUE TITLE
Unable to install packages due to error 

### ISSUE THREAD

**Issue by washbin** [esatya/rahat-agency#236]
I tried running rahat-agency locally but yarn is unable to install packages and the culprit seems to be `rumsan-ui` package in `package.json`.
![rumsan-ui-not-found](https://user-images.githubusercontent.com/76929116/196750117-bc833702-95f3-48b2-8caa-3c7769f416bd.png)

However, on further inspection, I found the package wasn't referenced throughout the the project. So removing the culprit from `package.json` should be alright.

**Comment by washbin** [comment]
this issue seems to have an active pr #234 and some other complications that arrive even after the removal of this specific package.
Some packages seems to be dependent on python2 which doesn't seem to be ideal.

**Comment by myanzik** [comment]
This pacakge was deprecated so it has beed removed with PR #234 . which is already merged
